### ISSUE TITLE
ELoggerManagerImp中的空指针

### ISSUE THREAD

**Issue by Penguinang** [cxxjava/cxxLog4j#1]
你好，我在运行你的CxxMina项目时候，遇到了空指针的错误
在`ELoggerManagerImp.cpp`中，有如下构造函数

```
ELoggerManagerImp::ELoggerManagerImp() : configFile(null), lastModified(0L) {
	loggers = new EConcurrentHashMap<EString, ELogger>();
	rootLogger = getLogger(ROOT_LOGGER_NAME);
}
```
另一指针 `configuration`并未在此处初始化，但是后面也有使用。在我这边最终引起了空指针的错误，是否有问题？谢谢

**Comment by cxxjava** [comment]
log4j.properties配置文件路径指对了吗？原版本找不到配置文件会导致空指针问题。

configFile的初始化是在"void ELoggerManagerImp::reset(const char* config) {...}"方法里设置的。

**Comment by Penguinang** [comment]
好的，谢谢。另外顺便问下，CxxMina项目中，在windows下跑的时候会遇到建立连接时等待卡死的问题，即下面的awaitUninterruptibly()无法返回
```
		sp<EConnectFuture> future = connector->connect(&addr);
		future->awaitUninterruptibly();
```
，同样的代码在linux下却没有问题，请问这个可能有什么原因吗？谢谢

**Comment by cxxjava** [comment]
awaitUninterruptibly()默认是一直阻塞等待的，如果无法连接会一直等待下去。
linux下会返回，有可能是linux下SO_RCVTIMEO设置起作用了。

**Comment by Penguinang** [comment]
或者换句话说，为什么linux下可以正常连接，windows就不能？可以提供一个思路吗？谢谢

**Comment by cxxjava** [comment]
是win下就无法建立连接吗？或者你加QQ群817520689面聊。

**Comment by Penguinang** [comment]
好的，谢谢
